- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
- yarn.lock
There is no contribute guide docs including the issue & pull-request template.
I added the CONTRIBUTING, ISSUE_TEMPLATE, PULL_REQUEST_TEMPLATE for developers to contribute this open-source.
> docs: Add CONTRIBUTING, ISSUE_TEMPLATE, PULL_REQUEST_TEMPLATE

- referenceFiles/test/helpers/constants.js
- referenceFiles/test/helpers/latestTime.js
- referenceFiles/test/helpers/shouldFail.js
- referenceFiles/test/helpers/time.js
- referenceFiles/test/helpers/web3.js
modules of referenceFiles/test/helpers are old version
update referenceFiles/test/helpers modules
> feat: update referenceFiles/test/helpers repo

- .gitignore
- lib/compile.js
- package.json
- scripts/deploy-service/index.js
- scripts/deploy-service/preProcess/checkError.js
- scripts/deploy-service/preProcess/compareConfigAndState.js
- scripts/deploy-service/preProcess/index.js
- scripts/deploy-service/processes/deployBusinesses.js
- scripts/deploy-service/processes/deployNonUpgradeables.js
- scripts/deploy-service/processes/deployProxies.js
- scripts/deploy-service/processes/deployRegistry.js
- scripts/deploy-service/processes/initNonUpgradeables.js
- scripts/deploy-service/processes/registerFileNames.js
- scripts/deploy-service/processes/upgradeAll.js
- scripts/deploy-service/utils/writeState.js
- scripts/init.js
- No styling at `haechi init`, `haechi -h` and `haechi deploy-service`
- Less information at package.json
- Styling at `haechi init`, `haechi -h` and `haechi deploy-service`
- Apply logo output when run `haechi init`
- Update information at package.json
> style: prettier init, deploy-service log style.

- .commitlintrc.js
- .travis.yml
- README.md
- package.json
- yarn.lock
- no rules for commit msg
- add rules for commit msg
> ci: add conventional-commit to travis-cli and add commitlint

- .github/PULL_REQUEST_TEMPLATE.md
- CONFIGURATION-ko.md
- CONFIGURATION.md
- README.md
- commands/README-ko.md
- commands/README.md
- README.md is not good to follow.
- just Korean version of README.md
- New README.md has created and old README.md is devided into commands/README.md and CONFIGURATION.md.
- add both kor and eng version of commands/README.md and CONFIGURATION.md.
Still, README-ko.md is needed.
> Add and update documentations.

- README.md
`npm install --global @haechi-labs/haechi-cli` command may be correct :)
> npm install --global haechi-cli is not working.

- CONTRIBUTING-ko.md
- CONTRIBUTING.md
No Eng version of CONTRIBUTING.md
No explanation about type of commit message
Add Eng version of CONTRIBUTING.md
Add explanation about type of commit message
> docs: add english version of CONTRIBUTING.md and update CONTRIBUTING

- packages/vvisp/contracts/test/DependencyB.sol
- packages/vvisp/contracts/test/DependencyD.sol
- packages/vvisp/scripts/deploy-service/processes/injectVar.js
- packages/vvisp/test/dummy/justNonUpgradeables.service1.json
- packages/vvisp/test/dummy/justNonUpgradeables.service2.json
- packages/vvisp/test/dummy/service1.json
- packages/vvisp/test/dummy/service2.json
If `constructorArguments` is described like
```
"constructorArguments": [
3,
"${contracts.DependencyD.address}",
"${variables.owner}"
]
```
variable injection wasn't work.
Fixed it.
> fix: fix bug #13

- CONTRIBUTING-ko.md
- CONTRIBUTING.md
- README.md
No install guide of lerna in CONTRIBUTING
There were Dapp, dapp, DApp
Weak Usage section in README
Legacy link of USCF pdf in README
Add install guide in CONTRIBUTING
Unify words to DApp in README
Refine usage section in README
Change links in README
> docs: refine documentations, CONTRIBUTING and README

- packages/vvisp/referenceFiles/contracts/Migrations.sol
- packages/vvisp/referenceFiles/package.json
No prettier when initializing project.
Add linter to initialized project.
Lint Migrations.sol
> Add prettier at init projects

- packages/vvisp/commands/README-ko.md
- packages/vvisp/commands/README.md
- packages/vvisp/referenceFiles/contracts/Migrations.sol
- packages/vvisp/referenceFiles/package.json
- packages/vvisp/referenceFiles/scripts/coverage.sh
Issue Number: #20 
No coverage scripts for initial projects.
Add coverage scripts for initial projects
> Add coverage at init projects #20

- packages/vvisp/README.md
- packages/vvisp/bin/commander.js
Issue Number: #28 
```bash
$ vvisp -v
error: unknown option `-v'
$ vvisp -version
error: unknown option `-v'
$ vvisp --version
0.1.9
```
```bash
$ vvisp -v
v0.1.9
$ vvisp -version
v0.1.9
$ vvisp --version
v0.1.9
```
Even if it was described as feature in #28, there are no tests because it is just version display.
> Fix version display

- packages/vvisp/scripts/deploy-service/preProcess/compareConfigAndState.js
- packages/vvisp/scripts/deploy-service/preProcess/compileAll.js
- packages/vvisp/scripts/deploy-service/preProcess/index.js
- packages/vvisp/test/scripts/deploy-service/index.test.js
Issue Number: #32 
Do not compile Proxy when you don't have any upgradeable contracts.
> fix: do not compile Proxy when there is no upgradeable contract #32

- packages/vvisp/bin/commander.js
> fix: add invalid command error handler

- packages/vvisp-utils/contracts/MyNFT.sol
- packages/vvisp-utils/package.json
- packages/vvisp-utils/src/compile.js
- packages/vvisp-utils/test/compile.test.js
Issue Number: #57 
findImports now enable to find .sol at node_modules
> fix: #57, findImports now enable to find .sol at node_modules

- packages/vvisp/contracts/test/Flattened.sol
- packages/vvisp/test/scripts/deploy-contract.test.js
`vvisp deploy-contract` test codes are added.
> test: add deploy-contract

- CONFIGURATION-ko.md
- CONFIGURATION.md
- packages/vvisp-utils/src/getWeb3.js
- packages/vvisp/bin/error.js
- packages/vvisp/referenceFiles/example.env
- packages/vvisp/scripts/deploy-contract.js
- packages/vvisp/scripts/deploy-service/index.js
- packages/vvisp/test/bin/error.test.js
Issue Number: #60 
If you want to connect with custom blockchain, set `.env` like below:
```
NETWORK= 'custom'
URL= 'your/link'
```
> feat: allow to connect with custom blockchain #60, code refine, add test

- packages/vvisp/scripts/console.js
> fix: modified to get address according to fileName and add try catch when call contract method

- packages/vvisp/package.json
- packages/vvisp/scripts/console.js
> fix: modified to accept array as input

- packages/vvisp/scripts/console.js
```
vvisp console
Index				Contract				Address
[0]				ContractA				0x1234...
>> show ContractA
=> FAIL
```
```
vvisp console
Index				Contract				Address
[0]				ContractA				0x1234...
>> show ContractA
[Method]			[Args]
methodA				[arg0]
methodB				[arg1, arg2]
```
> fix: vvisp console show [CONTRACT] regex fix

- packages/vvisp/package.json
- packages/vvisp/scripts/console.js
- packages/vvisp/test/scripts/console.test.js
> feat: add receipt.logs parser

- packages/vvisp/scripts/console.js
>  feat: add register command in console

- packages/vvisp-utils/package.json
- packages/vvisp-utils/src/compile.js
> fix: #80 adjust findImports

- packages/vvisp-utils/src/compile.js
- packages/vvisp-utils/src/compileAndDeploy.js
- packages/vvisp-utils/src/utils/compilerSupplier.js
- packages/vvisp-utils/test/compile.test.js
- packages/vvisp-utils/test/deploy.test.js
- packages/vvisp/scripts/abi-to-script/generateApis.js
- packages/vvisp/scripts/compile.js
- packages/vvisp/scripts/deploy-contract.js
- packages/vvisp/scripts/deploy-service/preProcess/compileAll.js
Use `printOrSilent()` function at `compile.js`
> Use printOrSilent at compile.js

- packages/vvisp/scripts/console.js
- packages/vvisp/test/dummy/test.proxy.state.vvisp.json
- packages/vvisp/test/scripts/console.test.js
> fix: register proxy address when proxy=true

- packages/vvisp/referenceFiles/package.json
- packages/vvisp/referenceFiles/test/Example.test.js
Cannot install solidity-coverage
Informal test code convention
Unify example test code convention
Make solidity-coverage be installed
> fix: example test case convention, fix package.json

- packages/vvisp-utils/src/Config.js
- packages/vvisp-utils/test/Config.test.js
- packages/vvisp/bin/commander.js
- packages/vvisp/bin/options.js
- packages/vvisp/commands/abi-to-script.js
- packages/vvisp/commands/compile.js
- packages/vvisp/commands/console.js
- packages/vvisp/commands/deploy-contract.js
- packages/vvisp/commands/deploy-service.js
Issue Number: #103 
Now those options are added
```
-n, --network
--gasPrice
--gasLimit
--from
--configFile
```
> feat: add command line options to change config

- packages/vvisp-utils/src/Config.js
- packages/vvisp-utils/src/sendTx.js
- packages/vvisp-utils/test/Config.test.js
- packages/vvisp-utils/test/dummy/sample.vvisp-config.js
Issue Number: #104 
default gasPrice: 10Gwei
default gasLimit: 6721975
compile optimizer: true with 200 runs
- [] Yes
> fix: change default config options

- packages/vvisp/template/index.js
- packages/vvisp/template/script.mustache
- packages/vvisp/test/dummy/sample.vvisp-config.js
- packages/vvisp/test/dummy/testContractApis/back/index.js
- packages/vvisp/test/dummy/testContractApis/back/js/HaechiV1.js
- packages/vvisp/test/scripts/abi-to-script/index.test.js
If you change your config after generating Contract, it does not change previous Contract.
Change Contract file structure and make it possible
> fix: fix bug that config does not change after generated

- packages/vvisp/scripts/console.js
- [] Tests for the changes have been added (for bug fixes / features)
- [] Docs have been added / updated (for bug fixes / features)
Issue Number: #116 
Now,
```
>> call Haechi hi
Error: There is no function name of hi
at Object.call [as run] (/Users/jchoy/dev/Haechi/vvisp/packages/vvisp/scripts/console.js:295:13)
at Object.run (/Users/jchoy/dev/Haechi/vvisp/packages/vvisp/scripts/console.js:144:40)
at process._tickCallback (internal/process/next_tick.js:68:7)
```
above error msg will be shown
> feat: handle error if there is no function when using console #116

- packages/vvisp/commands/README-ko.md
- packages/vvisp/commands/README.md
> docs: correct typo HEACHI -> HAECHI

- packages/vvisp/scripts/console.js
- packages/vvisp/template/script.mustache
Issue Number: #128 
A provider of contract instance will be same with the one provided from `--network` option.
> fix #128 "fix: support --network option for vvisp console command"

- .circleci/config.yml
> fix: upgrade ganache version

- packages/vvisp/commands/README-ko.md
- packages/vvisp/commands/README.md
- packages/vvisp/commands/deploy-service.js
- packages/vvisp/scripts/deploy-service/index.js
- packages/vvisp/test/scripts/deploy-service/index.test.js
Issue Number: #131 
Instead of `reset` option, `force` option is added.
> feat: add force option to deploy-service

- packages/vvisp/scripts/console.js
Issue Number: #142 
Console does not show undefined address contract anymore
> fix: console does not show undefined address contract anymore

- packages/vvisp/scripts/console.js
Issue Number: #133 
fix vvisp console logic to handle multiple return values.
> fix: multiple return values handling at console call function

- packages/vvisp/scripts/console.js
- packages/vvisp/test/scripts/console.test.js
Issue Number: #132 
It shows some guide rather than error messages.
> fix: show error logs if entering console command before gen-script

- .gitattributes
Add setting for solidity files
> chore: setting for solidity readability

- packages/vvisp-contracts/package.json
- packages/vvisp/commands/README-ko.md
- packages/vvisp/commands/README.md
- packages/vvisp/scripts/console.js
- packages/vvisp/template/script.mustache
- packages/vvisp/test/dummy/testContractApis/back/index.js
- packages/vvisp/test/dummy/testContractApis/back/js/HaechiV1.js
- packages/vvisp/test/scripts/console.test.js
If 2 deployed contracts has same contract name => console duplicates contracts.
Add name property and determine contracts in console by this.
> fix: hotfix-fix-console-contract-dup-bug

- README-ko.md
- README.md
- README_KLAYTN.md
No documentation about klaytn.
Add klaytn documentation.
> docs: add klaytn tutorial docs, update exists docs

- packages/vvisp/scripts/deploy-contract.js
> fix: fix bug about array arguments at deploy-contract

- packages/vvisp/scripts/deploy-service/index.js
- packages/vvisp/scripts/deploy-service/preProcess/index.js
There is no guide logs about `deploy-service -f`.
`deploy-service -f` guide comes out when `Nothing to upgrade` and `Service deployment paused`.
> feat: add forced deploy guide

- packages/vvisp/scripts/gen-script/generateApis.js
If the contract name is different with file name or there are multiple contracts in on file, `gen-script` couldn't generate all scripts.
Search all contracts and make their scripts
> fix: make generate scripts of all contracts in file

- packages/vvisp/referenceFiles/contracts/Migrations.sol
- packages/vvisp/referenceFiles/migrations/1_initial_migration.js
Update the version of `Migration.sol` and `migrations/` to latest truffle version.
> fix: update init package belong to latest truffle version

- packages/vvisp-utils/src/compileAndDeploy.js
- packages/vvisp-utils/src/getSTDInput.js
- packages/vvisp-utils/src/index.js
- packages/vvisp/scripts/console.js
- packages/vvisp/scripts/deploy-contract.js
- packages/vvisp/test/scripts/gen-script/index.test.js
Search contract name that is same as the file name.
If there are multiple contract in one file, the interactive console will be active.
If there is one contract, it will be deployed.
> feat: add interactive to deploy-contract to determine the exact contract

- packages/vvisp/scripts/console.js
- packages/vvisp/test/scripts/console.test.js
Belong to latest update of vvisp, now it determines the name prop of the state.vvisp.json.
> fix: fix console to determine the name prop of state.vvisp.json

- packages/vvisp-utils/src/compile.js
Issue Number: #64 
```
Warnings:
./contracts/test/SecondA.sol:16:9: Warning: This declaration shadows an existing declaration.
hi
^ (Relevant source part starts here and spans across multiple lines).
./contracts/test/SecondA.sol:7:5: The shadowed declaration is here:
bool initialized = false;
^----------------------^
Errors:
./contracts/test/SecondA.sol:16:9: DeclarationError: Identifier not found or not unique.
hi
^^
```
> style: prettier compile warnings #64

- packages/vvisp/bin/commander.js
- packages/vvisp/bin/options.js
- packages/vvisp/commands/README-ko.md
- packages/vvisp/commands/README.md
- packages/vvisp/commands/compile.js
- packages/vvisp/commands/deploy-contract.js
- packages/vvisp/commands/deploy-service.js
- packages/vvisp/commands/flatten.js
- packages/vvisp/commands/gen-script.js
- packages/vvisp/commands/init.js
`silent` option is attached to `vvisp` command, not `vvisp sub` command.
So, `vvisp sub -s` (e.g. `vvisp deploy-contract -s`) does not work.
It works now.
> fix: fix bug about silent not working

- packages/vvisp/commands/compile.js
- packages/vvisp/commands/console.js
- packages/vvisp/commands/deploy-contract.js
- packages/vvisp/commands/deploy-service.js
- packages/vvisp/commands/flatten.js
- packages/vvisp/commands/gen-script.js
- packages/vvisp/commands/init.js
Error msg occurred twice.
Just once.
> fix: fix bugs that the error msgs occurred twice

- README-ko.md
- README.md
- README_KLAYTN.md
- packages/vvisp/README.md
- packages/vvisp/commands/README-ko.md
- packages/vvisp/commands/README.md
- packages/vvisp/commands/compile.js
- packages/vvisp/commands/deploy-contract.js
- packages/vvisp/commands/deploy-service.js
- packages/vvisp/commands/flatten.js
- packages/vvisp/commands/gen-script.js
- packages/vvisp/commands/init.js
- packages/vvisp/scripts/init.js
- packages/vvisp/test/scripts/init.test.js
`vvisp init my-project`
1. make my-project dir
2. init there
> feat: add init package name

- packages/vvisp/commands/README-ko.md
- packages/vvisp/commands/README.md
- packages/vvisp/referenceFiles/.gitattributes
- packages/vvisp/referenceFiles/.gitignore
- packages/vvisp/referenceFiles/platform/ethereum/example.vvisp-config.js
- packages/vvisp/referenceFiles/platform/klaytn/example.vvisp-config.js
- packages/vvisp/test/scripts/init.test.js
Add `.gitattributes`.
Add a comment that guides user can use private key rather than mnemonic.
> feat: add .gitattribute to ref, add comments, update chore things in ref
